### ISSUE TITLE
Ошибки, если WAIT_FOR_MOST_PROFIT_UPGRADES=False

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#34]
После последнего обновления. Если в .env опция WAIT_FOR_MOST_PROFIT_UPGRADES=True, то всё ок. А вот если WAIT_FOR_MOST_PROFIT_UPGRADES=False тогда получаем следующее:

2024-07-29 17:27:17 | SUCCESS  | 155 - 000 | Successfully upgraded Antihacking shield to 15 lvl | Earn every hour: 1.81M (+284)
2024-07-29 17:27:17 | ERROR    | 309 - 000| Unknown error: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 274, in run
    await self.make_upgrades()
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 102, in make_upgrades
    most_profit_upgrade: Upgrade = available_upgrades[0]
                                   ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-07-29 17:27:21 | INFO     | 57 - 000| User id: -----| Last passive earn: +2.51k | Earn every hour: 1.81M | Balance: 65.35k
2024-07-29 17:27:29 | ERROR    | 309 - 000| Unknown error: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 274, in run
    await self.make_upgrades()
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 102, in make_upgrades
    most_profit_upgrade: Upgrade = available_upgrades[0]
                                   ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-07-29 17:27:33 | INFO     | 57 - 000| User id: -----| Last passive earn: +6.03k | Earn every hour: 1.81M | Balance: 71.37k
2024-07-29 17:27:35 | ERROR    | 309 - 000| Unknown error: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 274, in run
    await self.make_upgrades()
  File "C:\Users\User\Desktop\Daniil Hamster MiniGames\bot\core\tapper.py", line 102, in make_upgrades
    most_profit_upgrade: Upgrade = available_upgrades[0]
                                   ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

User id я специально убрал), а то вдруг палево)

**Comment by AnisovAleksey** [comment]
там наверное придется логику дейли комбо поменять чтобы нормально все это работало, а то чето сильно сложно получается. Пока хз когда смогу исправить
